### ISSUE TITLE
deploy instance using terraform

### ISSUE THREAD

**Issue by atoamaeto** [atoamaeto/openstak-tf-integration#1]
Someone help to create demo for deployment instance in openstack using terraform

**Comment by ilosaurus** [comment]
oke, will send some PR about terraform openstack

**Comment by ilosaurus** [comment]
Hello amaeto, 
can u check this PR #2

**Comment by atoamaeto** [comment]
Ok, already check and tested
Thanks

**Comment by atoamaeto** [comment]
already merge, thank so much!

**Comment by ilosaurus** [comment]
ur wlcome!
