### ISSUE TITLE
Update variable deployment instance openstack

### ISSUE THREAD

**Issue by atoamaeto** [atoamaeto/openstak-tf-integration#3]
Update variable security group deployment instance openstack.
Pls fork and PR.

Thanks.

**Comment by ilosaurus** [comment]
oke,  pls confirm the terraform version.

**Comment by atoamaeto** [comment]
terraform version v0.12.29.

**Comment by ilosaurus** [comment]
Oke noted thanks for update.

**Comment by ilosaurus** [comment]
Oke, pls merge.

**Comment by atoamaeto** [comment]
oke done. thanks @ilosaurus for PR.
